name: Nathan Nordby, Doc Creator Extraordinaire
markdown: kramdown
remote_theme: CloudCannon/aviator-jekyll-template
source: /docs
destination: /docs
permalink: blog/:year/:month/:day/:title
plugins:
  - jekyll-feed
